jobs:
  include:
    - stage: Windows build
      os: windows
      language: go
      go: "1.13"
      script:
        - go test -v ./tests/...
      before_deploy:
        - powershell -executionpolicy bypass -command "scripts/windows.ps1 -TravisOS ${TRAVIS_OS_NAME} -TravisArch ${TRAVIS_CPU_ARCH} -TravisTag ${TRAVIS_TAG}"
      deploy:
        provider: releases
        file_glob: true
        file: dist/*
        draft: true
        tag_name: $TRAVIS_TAG
        skip_cleanup: true
        token:
          secure: uTF8YQIFe9Au6Xq9DwqGW/e9JGOuzOXcCQsFtXGOLwQFhrKIGGtx8lr9dwRdrThNeAmpYUlJulwf/3Bq227rpKeYkbpkXLWTpBLfBHPde7Eqbj3VC/u9uxm9AkAnEqeFXeJhTFe+cxYjRuZTGGT3iFXwHMUI3t+EZX1DgVK5Q7H24FfIr2bTdstTySXqN67IiM6jMK89kUHEVDCuo8bG+52PaxXxy6Cp8jaDEeF0FbFeLw2mbwZ0pDj8y8y3qVG3mo9KuMhOF4XcqjhJWalDEbljBIebzzfAgnJmmdmsR6GmTrNzHf/IsnaF3YWFr0BO9ocTYu3pBgr4FHQ3mHqV7ALxhKxcAXT9OumtKzD6lRm3SfB4s+wGrYPMa+fakso5rpdTbXHsi178hAjfKrNywkyDMznsCDranlbLs7m3rEIIZSu7dM9zxmVlI0TgSx9xwUInS4QTTJ5sYSfAqJewBMtmxWDktTpaU+7TGpubF79tWLpPXvtfAx47m/R1pkgqP1Q0+e5hnFgapNELXITsunkUm5OvvCLiGtwt1+ZqwIOsGJVutzyf+QjW/KPYB2i52StIzPb/+xfpILV7GunbRzoUpdNHSzWhSNLIDtjQnGSNha9B/OXbNJRd4pya/SwB+uPDG3vbDqKMKHx7C4U7f9K/544iixsWRQUQSE81exs=
        on:
          tags: true
    - stage: OSX build
      os: osx
      language: go
      go: "1.13"
      script:
        - go test -v ./tests/...
      before_deploy:
        - brew install jshon
        - bash scripts/osx.sh
        - export RELEASE_NOTES=$(jshon -s "$(cat dist/RELEASE.md)")
      deploy:
        provider: releases
        file_glob: true
        file: dist/*
        draft: false
        tag_name: $TRAVIS_TAG
        skip_cleanup: true
        release_notes: ${RELEASE_NOTES}
        token:
          secure: uTF8YQIFe9Au6Xq9DwqGW/e9JGOuzOXcCQsFtXGOLwQFhrKIGGtx8lr9dwRdrThNeAmpYUlJulwf/3Bq227rpKeYkbpkXLWTpBLfBHPde7Eqbj3VC/u9uxm9AkAnEqeFXeJhTFe+cxYjRuZTGGT3iFXwHMUI3t+EZX1DgVK5Q7H24FfIr2bTdstTySXqN67IiM6jMK89kUHEVDCuo8bG+52PaxXxy6Cp8jaDEeF0FbFeLw2mbwZ0pDj8y8y3qVG3mo9KuMhOF4XcqjhJWalDEbljBIebzzfAgnJmmdmsR6GmTrNzHf/IsnaF3YWFr0BO9ocTYu3pBgr4FHQ3mHqV7ALxhKxcAXT9OumtKzD6lRm3SfB4s+wGrYPMa+fakso5rpdTbXHsi178hAjfKrNywkyDMznsCDranlbLs7m3rEIIZSu7dM9zxmVlI0TgSx9xwUInS4QTTJ5sYSfAqJewBMtmxWDktTpaU+7TGpubF79tWLpPXvtfAx47m/R1pkgqP1Q0+e5hnFgapNELXITsunkUm5OvvCLiGtwt1+ZqwIOsGJVutzyf+QjW/KPYB2i52StIzPb/+xfpILV7GunbRzoUpdNHSzWhSNLIDtjQnGSNha9B/OXbNJRd4pya/SwB+uPDG3vbDqKMKHx7C4U7f9K/544iixsWRQUQSE81exs=
        on:
          tags: true
